### ISSUE TITLE
Erreur python

### ISSUE THREAD

**Issue by vrolland78** [tmz42/heatzy#1]
Bonjour,
heatzy-cli fonctionne avec quelle version de python svp ? 
Sur ma raspbian quand je lance j'obtiens cela, vous auriez une idée svp ?
Merci
Vincent

 # heatzy-cli -h
Traceback (most recent call last):
  File "/usr/local/bin/heatzy-cli", line 4, in <module>
    __import__('pkg_resources').run_script('heatzy==0.0.6', 'heatzy-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1444, in run_script
    script_code = compile(script_text, script_filename,'exec')
  File "/usr/local/lib/python2.7/dist-packages/heatzy-0.0.6-py2.7.egg/EGG-INFO/scripts/heatzy-cli", line 38
    print('Mode not found', file=sys.stderr)
                                ^
SyntaxError: invalid syntax

**Comment by vrolland78** [comment]
J'ai vu qu'il fallait python3, autant pour moi. J'ai fait le nécessaire.
Cependant je n'arrive pas à lister les devices

$ heatzy-cli -u monmail -p monmail  -l
Traceback (most recent call last):
  File "/usr/local/bin/heatzy-cli", line 4, in <module>
    __import__('pkg_resources').run_script('heatzy==0.0.6', 'heatzy-cli')
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/dist-packages/heatzy-0.0.6-py3.4.egg/EGG-INFO/scripts/heatzy-cli", line 54, in <module>
  File "/usr/local/lib/python3.4/dist-packages/heatzy-0.0.6-py3.4.egg/EGG-INFO/scripts/heatzy-cli", line 21, in main
  File "/usr/local/lib/python3.4/dist-packages/heatzy-0.0.6-py3.4.egg/heatzy/heatzy.py", line 78, in getHeatzyDevices
  File "/usr/local/lib/python3.4/dist-packages/heatzy-0.0.6-py3.4.egg/heatzy/heatzy.py", line 99, in __init__
  File "/usr/local/lib/python3.4/dist-packages/heatzy-0.0.6-py3.4.egg/heatzy/heatzy.py", line 115, in status
KeyError: 'mode'

**Comment by deennoo** [comment]
@vrolland78 quels devices avez vous ?

**Comment by vrolland78** [comment]
J'avais un problème avec la version de python finalement.
2 version cohabite sur ma debian une 2.7 et une 3.4 mais c'est la 2.7 qui était utilisée par défaut
via les commande "update-alternatives" j'ai pu modifier cela.

**Comment by vrolland78** [comment]
J'ai par contre toujours un soucis régulier dans le sens ou si je n'utilise pas l'appli du téléphone pendant plusieurs jours heatzy-cli fini par ne plus fonctionner. Je me connecte sur l'appli et la le fonctionne de nouveau...j'utilise 2 module heatzy fil pilote pour mes radiateurs.

**Comment by vrolland78** [comment]
problème python réglé
