### ISSUE TITLE
Heatzy FLAM

### ISSUE THREAD

**Issue by deennoo** [tmz42/heatzy#2]
Bonjour,

J'ai un Pilote v1 ainsi qu'un FLAM.

Les deux etant sur le meme compte, je rencontre une erreur lors du listage des devices : 

`Traceback (most recent call last):
  File "/usr/local/bin/heatzy-cli", line 4, in <module>
    __import__('pkg_resources').run_script('heatzy==0.0.6', 'heatzy-cli')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/site-packages/heatzy-0.0.6-py3.5.egg/EGG-INFO/scripts/heatzy-cli", line 54, in <module>
  File "/usr/local/lib/python3.5/site-packages/heatzy-0.0.6-py3.5.egg/EGG-INFO/scripts/heatzy-cli", line 21, in main
  File "/usr/local/lib/python3.5/site-packages/heatzy-0.0.6-py3.5.egg/heatzy/heatzy.py", line 78, in getHeatzyDevices
  File "/usr/local/lib/python3.5/site-packages/heatzy-0.0.6-py3.5.egg/heatzy/heatzy.py", line 99, in __init__
  File "/usr/local/lib/python3.5/site-packages/heatzy-0.0.6-py3.5.egg/heatzy/heatzy.py", line 119, in status
KeyError: 'Flam_Week2'
`

**Comment by tmz42** [comment]
Bonjour @deennoo,

Je regarde ça. A priori vu que les Flam ne sont pas supportés dans la bibliothèque, à l'ajout ça coince.

**Comment by tmz42** [comment]
Bonjour @deennoo, je n'arrive pas à trouver la sortie d'un Flam sur heatzy...

Pourriez-vous s'il vous plaît passer la commande suivante avec le DID de votre Flam s'il vous plaît?
`curl -X GET --header 'Accept: application/json' --header 'X-Gizwits-Application-Id: 70a66ff039d41b4a220e198b0fcc8b3' 'https://euapi.gizwits.com/app/devdata/​{did}​​/latest'`
